/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "LaravelAppPoC-Scheduler": {
      "service": string
      "type": "sst.aws.Service"
    }
    "LaravelAppPoC-Web": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "RedisCluster": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "SSTVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
